/* ─────────────────────────────────────────────────
   EMAIL TEMPLATE BUILDER
   Generates branded HTML email strings for each
   execution layer module. Inline CSS for email
   client compatibility.
───────────────────────────────────────────────── */

/**
 * Build a complete HTML email string.
 *
 * @param {'health-diagnostic'|'money-leaks'|'sop-delivery'|'lead-email'} module
 * @param {Object} data — module-specific data
 * @param {Object} branding — { primaryColor, accentColor, companyName }
 * @returns {string} — full HTML email string
 */
export function buildEmailHtml(module, data, branding) {
    const { primaryColor = '#2C3FB8', accentColor = '#3366FF', companyName = 'SBOS' } = branding;

    let bodyContent = '';

    switch (module) {
        case 'health-diagnostic':
            bodyContent = buildDiagnosticBody(data, primaryColor, accentColor);
            break;
        case 'money-leaks':
            bodyContent = buildMoneyLeaksBody(data, primaryColor, accentColor);
            break;
        case 'sop-delivery':
            bodyContent = buildSopBody(data, primaryColor, accentColor);
            break;
        case 'lead-email':
            bodyContent = buildLeadEmailBody(data, primaryColor, accentColor);
            break;
        default:
            bodyContent = '<p>Unknown module.</p>';
    }

    return wrapInLayout(bodyContent, companyName, primaryColor, accentColor);
}

/* ─────────── LAYOUT WRAPPER ─────────── */

function wrapInLayout(bodyContent, companyName, primaryColor, accentColor) {
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${companyName} — SBOS Report</title>
</head>
<body style="margin:0;padding:0;background-color:#f4f6fa;font-family:'Helvetica Neue',Arial,sans-serif;color:#101426;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f4f6fa;">
<tr><td align="center" style="padding:32px 16px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.06);">

<!-- Header -->
<tr>
<td style="background:linear-gradient(135deg, ${primaryColor}, ${accentColor});padding:28px 32px;">
<h1 style="margin:0;font-size:20px;font-weight:700;color:#ffffff;letter-spacing:-0.3px;">${companyName}</h1>
<p style="margin:4px 0 0;font-size:11px;color:rgba(255,255,255,0.75);text-transform:uppercase;letter-spacing:1px;">SBOS Business Report</p>
</td>
</tr>

<!-- Body -->
<tr>
<td style="padding:32px;">
${bodyContent}
</td>
</tr>

<!-- Footer -->
<tr>
<td style="padding:24px 32px;background-color:#f8faff;border-top:1px solid #e8ecf4;">
<p style="margin:0;font-size:11px;color:#5e6b8a;line-height:1.6;">
Generated by <strong>SBOS Demo</strong> — Small Business Operating System<br>
This report was created during a demo session with sample business data.
</p>
</td>
</tr>

</table>
</td></tr>
</table>
</body>
</html>`;
}

/* ─────────── HEALTH DIAGNOSTIC ─────────── */

function buildDiagnosticBody(data, primaryColor, accentColor) {
    const { overallScore = 0, categories = [], quickWins = [], risks = [] } = data;
    const scoreColor = overallScore >= 75 ? '#18C37E' : overallScore >= 50 ? '#F5A524' : '#EF4444';

    const categoryRows = categories.map(cat => {
        const statusColors = {
            stable: '#18C37E',
            'at-risk': '#F5A524',
            critical: '#EF4444',
        };
        const color = statusColors[cat.status] || '#6B7280';
        return `<tr>
            <td style="padding:8px 0;font-size:13px;color:#101426;font-weight:600;">${cat.name}</td>
            <td style="padding:8px 0;text-align:center;">
                <div style="background-color:#f4f6fa;border-radius:99px;height:8px;width:100%;overflow:hidden;">
                    <div style="background-color:${color};height:100%;width:${cat.score}%;border-radius:99px;"></div>
                </div>
            </td>
            <td style="padding:8px 0 8px 12px;text-align:right;font-size:13px;font-weight:700;color:${color};">${cat.score}</td>
        </tr>`;
    }).join('');

    const winItems = quickWins.map(w => `<li style="padding:4px 0;font-size:13px;color:#101426;">✅ ${w}</li>`).join('');
    const riskItems = risks.map(r => `<li style="padding:4px 0;font-size:13px;color:#101426;">⚠️ ${r}</li>`).join('');

    return `
<h2 style="margin:0 0 4px;font-size:16px;color:${primaryColor};">Weekly Health Diagnostic</h2>
<p style="margin:0 0 24px;font-size:13px;color:#5e6b8a;">Your business health snapshot for this week.</p>

<!-- Score -->
<div style="text-align:center;padding:24px;background-color:#f8faff;border-radius:12px;margin-bottom:24px;">
<p style="margin:0;font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#5e6b8a;">Overall Score</p>
<p style="margin:8px 0 4px;font-size:48px;font-weight:800;color:${scoreColor};line-height:1;">${overallScore}</p>
<p style="margin:0;font-size:12px;color:#5e6b8a;">/100</p>
</div>

<!-- Categories -->
<h3 style="margin:0 0 12px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#5e6b8a;">Category Breakdown</h3>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
${categoryRows}
</table>

<!-- Quick Wins -->
${quickWins.length ? `
<h3 style="margin:0 0 8px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#18C37E;">Quick Wins</h3>
<ul style="margin:0 0 24px;padding-left:0;list-style:none;">${winItems}</ul>
` : ''}

<!-- Risks -->
${risks.length ? `
<h3 style="margin:0 0 8px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#F5A524;">Identified Risks</h3>
<ul style="margin:0;padding-left:0;list-style:none;">${riskItems}</ul>
` : ''}`;
}

/* ─────────── MONEY LEAKS ─────────── */

function buildMoneyLeaksBody(data, primaryColor, accentColor) {
    const { totalMonthlyWaste = '$0', leaks = [], recommendations = [] } = data;

    const leakRows = leaks.map(leak => `<tr>
        <td style="padding:8px 0;font-size:13px;color:#101426;border-bottom:1px solid #f0f0f5;">${leak.tool || leak.description || leak.name || 'Unknown'}</td>
        <td style="padding:8px 0;text-align:right;font-size:13px;font-weight:700;color:#EF4444;border-bottom:1px solid #f0f0f5;">${leak.monthlyCost || leak.amount || ''}</td>
    </tr>`).join('');

    const recItems = recommendations.map(r => {
        const text = typeof r === 'string' ? r : (r.action || r.description || JSON.stringify(r));
        return `<li style="padding:4px 0;font-size:13px;color:#101426;">💡 ${text}</li>`;
    }).join('');

    return `
<h2 style="margin:0 0 4px;font-size:16px;color:${primaryColor};">Weekly Money Leak Report</h2>
<p style="margin:0 0 24px;font-size:13px;color:#5e6b8a;">Areas where your business may be losing money.</p>

<!-- Total Waste -->
<div style="text-align:center;padding:24px;background-color:#FEF2F2;border-radius:12px;margin-bottom:24px;">
<p style="margin:0;font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#5e6b8a;">Estimated Monthly Waste</p>
<p style="margin:8px 0 0;font-size:36px;font-weight:800;color:#EF4444;line-height:1;">${totalMonthlyWaste}</p>
</div>

<!-- Leak Table -->
${leaks.length ? `
<h3 style="margin:0 0 12px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:#5e6b8a;">Top Leaks</h3>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:24px;">
${leakRows}
</table>
` : ''}

<!-- Recommendations -->
${recommendations.length ? `
<h3 style="margin:0 0 8px;font-size:13px;text-transform:uppercase;letter-spacing:1px;color:${accentColor};">Recommendations</h3>
<ul style="margin:0;padding-left:0;list-style:none;">${recItems}</ul>
` : ''}`;
}

/* ─────────── SOP DELIVERY ─────────── */

function buildSopBody(data, primaryColor, accentColor) {
    const { sopTitle = 'SOP', steps = [], owner = '', frequency = '', estimatedTime = '' } = data;

    const stepRows = steps.map(step => `
<tr>
<td style="padding:12px 0;border-bottom:1px solid #f0f0f5;vertical-align:top;">
    <div style="display:inline-block;width:28px;height:28px;border-radius:8px;background-color:${accentColor};color:#fff;font-size:12px;font-weight:700;text-align:center;line-height:28px;margin-right:12px;vertical-align:top;">${step.number || ''}</div>
    <div style="display:inline-block;vertical-align:top;max-width:calc(100% - 44px);">
        <p style="margin:0;font-size:13px;font-weight:600;color:#101426;">${step.action || ''}</p>
        <p style="margin:4px 0 0;font-size:11px;color:#5e6b8a;">
            ${step.owner ? `👤 ${step.owner}` : ''} ${step.timing ? `• ⏱ ${step.timing}` : ''}
        </p>
        ${step.tools?.length ? `<p style="margin:4px 0 0;font-size:10px;color:#5e6b8a;">🔧 ${step.tools.join(', ')}</p>` : ''}
        ${step.notes ? `<p style="margin:4px 0 0;font-size:11px;color:#5e6b8a;font-style:italic;">💡 ${step.notes}</p>` : ''}
    </div>
</td>
</tr>`).join('');

    return `
<h2 style="margin:0 0 4px;font-size:16px;color:${primaryColor};">${sopTitle}</h2>
<p style="margin:0 0 16px;font-size:13px;color:#5e6b8a;">Standard Operating Procedure</p>

<!-- SOP Metadata -->
<div style="padding:16px;background-color:#f8faff;border-radius:12px;margin-bottom:24px;font-size:12px;color:#5e6b8a;">
    ${owner ? `<span>👤 Owner: <strong style="color:#101426;">${owner}</strong></span> &nbsp;&nbsp;` : ''}
    ${frequency ? `<span>🔄 ${frequency}</span> &nbsp;&nbsp;` : ''}
    ${estimatedTime ? `<span>⏱ ~${estimatedTime}</span>` : ''}
</div>

<!-- Steps -->
<table role="presentation" width="100%" cellpadding="0" cellspacing="0">
${stepRows}
</table>`;
}

/* ─────────── LEAD EMAIL (First Touchpoint) ─────────── */

function buildLeadEmailBody(data, primaryColor, accentColor) {
    const { subject = '', body = '', clientName = '', clientCompany = '' } = data;

    // The lead email IS the touchpoint content — not a report wrapper.
    // It should look like a real business email, not a report.
    return `
<p style="margin:0 0 16px;font-size:14px;color:#101426;line-height:1.7;">
${body.replace(/\n/g, '<br>')}
</p>`;
}
